/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFeeSplitter } from "./IFeeSplitter";
export type { IMerkleVesting } from "./IMerkleVesting";
export type { PresaleRound } from "./PresaleRound";
