/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FeeSplitter {
  export type FeeConfigStruct = {
    totalBps: BigNumberish;
    treasuryBps: BigNumberish;
    referralPoolBps: BigNumberish;
    sbtStakingBps: BigNumberish;
  };

  export type FeeConfigStructOutput = [
    totalBps: bigint,
    treasuryBps: bigint,
    referralPoolBps: bigint,
    sbtStakingBps: bigint
  ] & {
    totalBps: bigint;
    treasuryBps: bigint;
    referralPoolBps: bigint;
    sbtStakingBps: bigint;
  };
}

export interface FeeSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "PRESALE_ROLE"
      | "distributeFeeERC20"
      | "distributeFeeNative"
      | "feeConfig"
      | "getRoleAdmin"
      | "grantPresaleRole"
      | "grantRole"
      | "hasRole"
      | "referralPoolVault"
      | "renounceRole"
      | "revokeRole"
      | "sbtStakingVault"
      | "setFeeConfig"
      | "setReferralPoolVault"
      | "setSbtStakingVault"
      | "setTreasuryVault"
      | "supportsInterface"
      | "treasuryVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollected"
      | "FeeConfigUpdated"
      | "FeeSplit"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "VaultUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRESALE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFeeERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFeeNative",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPresaleRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralPoolVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sbtStakingVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfig",
    values: [FeeSplitter.FeeConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralPoolVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSbtStakingVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryVault",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRESALE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFeeERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFeeNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantPresaleRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralPoolVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sbtStakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralPoolVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSbtStakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryVault",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [token: AddressLike, totalAmount: BigNumberish];
  export type OutputTuple = [token: string, totalAmount: bigint];
  export interface OutputObject {
    token: string;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigUpdatedEvent {
  export type InputTuple = [newConfig: FeeSplitter.FeeConfigStruct];
  export type OutputTuple = [newConfig: FeeSplitter.FeeConfigStructOutput];
  export interface OutputObject {
    newConfig: FeeSplitter.FeeConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeSplitEvent {
  export type InputTuple = [
    vault: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    bps: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    token: string,
    amount: bigint,
    bps: bigint
  ];
  export interface OutputObject {
    vault: string;
    token: string;
    amount: bigint;
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUpdatedEvent {
  export type InputTuple = [vaultType: string, newVault: AddressLike];
  export type OutputTuple = [vaultType: string, newVault: string];
  export interface OutputObject {
    vaultType: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): FeeSplitter;
  waitForDeployment(): Promise<this>;

  interface: FeeSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PRESALE_ROLE: TypedContractMethod<[], [string], "view">;

  distributeFeeERC20: TypedContractMethod<
    [token: AddressLike, totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeFeeNative: TypedContractMethod<[], [void], "payable">;

  feeConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalBps: bigint;
        treasuryBps: bigint;
        referralPoolBps: bigint;
        sbtStakingBps: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantPresaleRole: TypedContractMethod<
    [presale: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  referralPoolVault: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sbtStakingVault: TypedContractMethod<[], [string], "view">;

  setFeeConfig: TypedContractMethod<
    [newConfig: FeeSplitter.FeeConfigStruct],
    [void],
    "nonpayable"
  >;

  setReferralPoolVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setSbtStakingVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasuryVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasuryVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRESALE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeFeeERC20"
  ): TypedContractMethod<
    [token: AddressLike, totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeFeeNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "feeConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalBps: bigint;
        treasuryBps: bigint;
        referralPoolBps: bigint;
        sbtStakingBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantPresaleRole"
  ): TypedContractMethod<[presale: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralPoolVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sbtStakingVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFeeConfig"
  ): TypedContractMethod<
    [newConfig: FeeSplitter.FeeConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReferralPoolVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSbtStakingVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasuryVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigUpdated"
  ): TypedContractEvent<
    FeeConfigUpdatedEvent.InputTuple,
    FeeConfigUpdatedEvent.OutputTuple,
    FeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeSplit"
  ): TypedContractEvent<
    FeeSplitEvent.InputTuple,
    FeeSplitEvent.OutputTuple,
    FeeSplitEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUpdated"
  ): TypedContractEvent<
    VaultUpdatedEvent.InputTuple,
    VaultUpdatedEvent.OutputTuple,
    VaultUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeeConfigUpdated(tuple)": TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;
    FeeConfigUpdated: TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;

    "FeeSplit(address,address,uint256,uint256)": TypedContractEvent<
      FeeSplitEvent.InputTuple,
      FeeSplitEvent.OutputTuple,
      FeeSplitEvent.OutputObject
    >;
    FeeSplit: TypedContractEvent<
      FeeSplitEvent.InputTuple,
      FeeSplitEvent.OutputTuple,
      FeeSplitEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "VaultUpdated(string,address)": TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
    VaultUpdated: TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
  };
}
