/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as presaleFactorySol from "./PresaleFactory.sol";
export type { presaleFactorySol };
import type * as presaleRoundSol from "./PresaleRound.sol";
export type { presaleRoundSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { FeeSplitter } from "./FeeSplitter";
export type { MerkleVesting } from "./MerkleVesting";
