/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PresaleFactory {
  export type CreatePresaleParamsStruct = {
    projectToken: AddressLike;
    paymentToken: AddressLike;
    softCap: BigNumberish;
    hardCap: BigNumberish;
    minContribution: BigNumberish;
    maxContribution: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    projectOwner: AddressLike;
  };

  export type CreatePresaleParamsStructOutput = [
    projectToken: string,
    paymentToken: string,
    softCap: bigint,
    hardCap: bigint,
    minContribution: bigint,
    maxContribution: bigint,
    startTime: bigint,
    endTime: bigint,
    projectOwner: string
  ] & {
    projectToken: string;
    paymentToken: string;
    softCap: bigint;
    hardCap: bigint;
    minContribution: bigint;
    maxContribution: bigint;
    startTime: bigint;
    endTime: bigint;
    projectOwner: string;
  };

  export type VestingParamsStruct = {
    tgeUnlockBps: BigNumberish;
    cliffDuration: BigNumberish;
    vestingDuration: BigNumberish;
  };

  export type VestingParamsStructOutput = [
    tgeUnlockBps: bigint,
    cliffDuration: bigint,
    vestingDuration: bigint
  ] & { tgeUnlockBps: bigint; cliffDuration: bigint; vestingDuration: bigint };

  export type LPLockPlanStruct = {
    lockMonths: BigNumberish;
    dexId: BytesLike;
    liquidityPercent: BigNumberish;
  };

  export type LPLockPlanStructOutput = [
    lockMonths: bigint,
    dexId: string,
    liquidityPercent: bigint
  ] & { lockMonths: bigint; dexId: string; liquidityPercent: bigint };
}

export interface PresaleFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FACTORY_ADMIN_ROLE"
      | "createPresale"
      | "feeSplitter"
      | "getPresaleDetails"
      | "getRoleAdmin"
      | "getScheduleSalt"
      | "getVestingForRound"
      | "grantRole"
      | "hasRole"
      | "presaleCount"
      | "renounceRole"
      | "revokeRole"
      | "roundToComplianceHash"
      | "roundToLPPlan"
      | "roundToScheduleSalt"
      | "roundToVesting"
      | "rounds"
      | "supportsInterface"
      | "timelockExecutor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LPPlanRecorded"
      | "PresaleCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RolesGranted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FACTORY_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPresale",
    values: [
      PresaleFactory.CreatePresaleParamsStruct,
      PresaleFactory.VestingParamsStruct,
      PresaleFactory.LPLockPlanStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeSplitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPresaleDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleSalt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingForRound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "presaleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roundToComplianceHash",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roundToLPPlan",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roundToScheduleSalt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roundToVesting",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockExecutor",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FACTORY_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPresaleDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingForRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presaleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roundToComplianceHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundToLPPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundToScheduleSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundToVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockExecutor",
    data: BytesLike
  ): Result;
}

export namespace LPPlanRecordedEvent {
  export type InputTuple = [
    round: AddressLike,
    lockMonths: BigNumberish,
    dexId: BytesLike,
    liquidityPercent: BigNumberish
  ];
  export type OutputTuple = [
    round: string,
    lockMonths: bigint,
    dexId: string,
    liquidityPercent: bigint
  ];
  export interface OutputObject {
    round: string;
    lockMonths: bigint;
    dexId: string;
    liquidityPercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresaleCreatedEvent {
  export type InputTuple = [
    presaleId: BigNumberish,
    round: AddressLike,
    vesting: AddressLike,
    scheduleSalt: BytesLike,
    complianceHash: BytesLike
  ];
  export type OutputTuple = [
    presaleId: bigint,
    round: string,
    vesting: string,
    scheduleSalt: string,
    complianceHash: string
  ];
  export interface OutputObject {
    presaleId: bigint;
    round: string;
    vesting: string;
    scheduleSalt: string;
    complianceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RolesGrantedEvent {
  export type InputTuple = [vesting: AddressLike, rootSetter: AddressLike];
  export type OutputTuple = [vesting: string, rootSetter: string];
  export interface OutputObject {
    vesting: string;
    rootSetter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PresaleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PresaleFactory;
  waitForDeployment(): Promise<this>;

  interface: PresaleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FACTORY_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  createPresale: TypedContractMethod<
    [
      params: PresaleFactory.CreatePresaleParamsStruct,
      vestingParams: PresaleFactory.VestingParamsStruct,
      lpPlan: PresaleFactory.LPLockPlanStruct,
      complianceHash: BytesLike
    ],
    [[string, string] & { round: string; vesting: string }],
    "nonpayable"
  >;

  feeSplitter: TypedContractMethod<[], [string], "view">;

  getPresaleDetails: TypedContractMethod<
    [presaleId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        PresaleFactory.LPLockPlanStructOutput
      ] & {
        round: string;
        vesting: string;
        scheduleSalt: string;
        complianceHash: string;
        lpPlan: PresaleFactory.LPLockPlanStructOutput;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getScheduleSalt: TypedContractMethod<[round: AddressLike], [string], "view">;

  getVestingForRound: TypedContractMethod<
    [round: AddressLike],
    [string],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  presaleCount: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  roundToComplianceHash: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  roundToLPPlan: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint] & {
        lockMonths: bigint;
        dexId: string;
        liquidityPercent: bigint;
      }
    ],
    "view"
  >;

  roundToScheduleSalt: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  roundToVesting: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  rounds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  timelockExecutor: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FACTORY_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPresale"
  ): TypedContractMethod<
    [
      params: PresaleFactory.CreatePresaleParamsStruct,
      vestingParams: PresaleFactory.VestingParamsStruct,
      lpPlan: PresaleFactory.LPLockPlanStruct,
      complianceHash: BytesLike
    ],
    [[string, string] & { round: string; vesting: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeSplitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPresaleDetails"
  ): TypedContractMethod<
    [presaleId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        PresaleFactory.LPLockPlanStructOutput
      ] & {
        round: string;
        vesting: string;
        scheduleSalt: string;
        complianceHash: string;
        lpPlan: PresaleFactory.LPLockPlanStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getScheduleSalt"
  ): TypedContractMethod<[round: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVestingForRound"
  ): TypedContractMethod<[round: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "presaleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roundToComplianceHash"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "roundToLPPlan"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint] & {
        lockMonths: bigint;
        dexId: string;
        liquidityPercent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roundToScheduleSalt"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "roundToVesting"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelockExecutor"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LPPlanRecorded"
  ): TypedContractEvent<
    LPPlanRecordedEvent.InputTuple,
    LPPlanRecordedEvent.OutputTuple,
    LPPlanRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PresaleCreated"
  ): TypedContractEvent<
    PresaleCreatedEvent.InputTuple,
    PresaleCreatedEvent.OutputTuple,
    PresaleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RolesGranted"
  ): TypedContractEvent<
    RolesGrantedEvent.InputTuple,
    RolesGrantedEvent.OutputTuple,
    RolesGrantedEvent.OutputObject
  >;

  filters: {
    "LPPlanRecorded(address,uint256,bytes32,uint256)": TypedContractEvent<
      LPPlanRecordedEvent.InputTuple,
      LPPlanRecordedEvent.OutputTuple,
      LPPlanRecordedEvent.OutputObject
    >;
    LPPlanRecorded: TypedContractEvent<
      LPPlanRecordedEvent.InputTuple,
      LPPlanRecordedEvent.OutputTuple,
      LPPlanRecordedEvent.OutputObject
    >;

    "PresaleCreated(uint256,address,address,bytes32,bytes32)": TypedContractEvent<
      PresaleCreatedEvent.InputTuple,
      PresaleCreatedEvent.OutputTuple,
      PresaleCreatedEvent.OutputObject
    >;
    PresaleCreated: TypedContractEvent<
      PresaleCreatedEvent.InputTuple,
      PresaleCreatedEvent.OutputTuple,
      PresaleCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RolesGranted(address,address)": TypedContractEvent<
      RolesGrantedEvent.InputTuple,
      RolesGrantedEvent.OutputTuple,
      RolesGrantedEvent.OutputObject
    >;
    RolesGranted: TypedContractEvent<
      RolesGrantedEvent.InputTuple,
      RolesGrantedEvent.OutputTuple,
      RolesGrantedEvent.OutputObject
    >;
  };
}
