/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeSplitterExt,
  IFeeSplitterExtInterface,
} from "../../../contracts/PresaleFactory.sol/IFeeSplitterExt";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "presale",
        type: "address",
      },
    ],
    name: "grantPresaleRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeSplitterExt__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeSplitterExtInterface {
    return new Interface(_abi) as IFeeSplitterExtInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeSplitterExt {
    return new Contract(address, _abi, runner) as unknown as IFeeSplitterExt;
  }
}
