/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeSplitter,
  IFeeSplitterInterface,
} from "../../../contracts/PresaleRound.sol/IFeeSplitter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "distributeFeeERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "distributeFeeNative",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IFeeSplitter__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeSplitterInterface {
    return new Interface(_abi) as IFeeSplitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeSplitter {
    return new Contract(address, _abi, runner) as unknown as IFeeSplitter;
  }
}
