/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMerkleVesting,
  IMerkleVestingInterface,
} from "../../../contracts/PresaleRound.sol/IMerkleVesting";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "totalAllocated",
        type: "uint256",
      },
    ],
    name: "setMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMerkleVesting__factory {
  static readonly abi = _abi;
  static createInterface(): IMerkleVestingInterface {
    return new Interface(_abi) as IMerkleVestingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMerkleVesting {
    return new Contract(address, _abi, runner) as unknown as IMerkleVesting;
  }
}
