/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlueCheckRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRICE_USD"
      | "REFERRAL_POOL_SHARE"
      | "TREASURY_SHARE"
      | "checkBlueCheck"
      | "emergencyWithdraw"
      | "getRequiredBNB"
      | "hasBlueCheck"
      | "manualPriceBNB"
      | "owner"
      | "pause"
      | "paused"
      | "priceOracle"
      | "purchaseBlueCheck"
      | "purchaseTimestamp"
      | "referralPool"
      | "renounceOwnership"
      | "totalBNBCollected"
      | "totalPurchases"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateManualPrice"
      | "updateReferralPool"
      | "updateTreasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlueCheckPurchased"
      | "ManualPriceUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ReferralPoolUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRICE_USD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_POOL_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkBlueCheck",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredBNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBlueCheck",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualPriceBNB",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseBlueCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBNBCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPurchases",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateManualPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReferralPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "PRICE_USD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_POOL_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBlueCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasBlueCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualPriceBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseBlueCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBNBCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateManualPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReferralPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
}

export namespace BlueCheckPurchasedEvent {
  export type InputTuple = [
    user: AddressLike,
    amountPaid: BigNumberish,
    treasuryAmount: BigNumberish,
    referralPoolAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amountPaid: bigint,
    treasuryAmount: bigint,
    referralPoolAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amountPaid: bigint;
    treasuryAmount: bigint;
    referralPoolAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralPoolUpdatedEvent {
  export type InputTuple = [oldPool: AddressLike, newPool: AddressLike];
  export type OutputTuple = [oldPool: string, newPool: string];
  export interface OutputObject {
    oldPool: string;
    newPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlueCheckRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BlueCheckRegistry;
  waitForDeployment(): Promise<this>;

  interface: BlueCheckRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRICE_USD: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_POOL_SHARE: TypedContractMethod<[], [bigint], "view">;

  TREASURY_SHARE: TypedContractMethod<[], [bigint], "view">;

  checkBlueCheck: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRequiredBNB: TypedContractMethod<[], [bigint], "view">;

  hasBlueCheck: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  manualPriceBNB: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  purchaseBlueCheck: TypedContractMethod<[], [void], "payable">;

  purchaseTimestamp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referralPool: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalBNBCollected: TypedContractMethod<[], [bigint], "view">;

  totalPurchases: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateManualPrice: TypedContractMethod<
    [_newPriceBNB: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateReferralPool: TypedContractMethod<
    [_newPool: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRICE_USD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_POOL_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkBlueCheck"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRequiredBNB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasBlueCheck"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manualPriceBNB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseBlueCheck"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "purchaseTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBNBCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPurchases"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateManualPrice"
  ): TypedContractMethod<[_newPriceBNB: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReferralPool"
  ): TypedContractMethod<[_newPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BlueCheckPurchased"
  ): TypedContractEvent<
    BlueCheckPurchasedEvent.InputTuple,
    BlueCheckPurchasedEvent.OutputTuple,
    BlueCheckPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ManualPriceUpdated"
  ): TypedContractEvent<
    ManualPriceUpdatedEvent.InputTuple,
    ManualPriceUpdatedEvent.OutputTuple,
    ManualPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralPoolUpdated"
  ): TypedContractEvent<
    ReferralPoolUpdatedEvent.InputTuple,
    ReferralPoolUpdatedEvent.OutputTuple,
    ReferralPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BlueCheckPurchased(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BlueCheckPurchasedEvent.InputTuple,
      BlueCheckPurchasedEvent.OutputTuple,
      BlueCheckPurchasedEvent.OutputObject
    >;
    BlueCheckPurchased: TypedContractEvent<
      BlueCheckPurchasedEvent.InputTuple,
      BlueCheckPurchasedEvent.OutputTuple,
      BlueCheckPurchasedEvent.OutputObject
    >;

    "ManualPriceUpdated(uint256,uint256)": TypedContractEvent<
      ManualPriceUpdatedEvent.InputTuple,
      ManualPriceUpdatedEvent.OutputTuple,
      ManualPriceUpdatedEvent.OutputObject
    >;
    ManualPriceUpdated: TypedContractEvent<
      ManualPriceUpdatedEvent.InputTuple,
      ManualPriceUpdatedEvent.OutputTuple,
      ManualPriceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralPoolUpdated(address,address)": TypedContractEvent<
      ReferralPoolUpdatedEvent.InputTuple,
      ReferralPoolUpdatedEvent.OutputTuple,
      ReferralPoolUpdatedEvent.OutputObject
    >;
    ReferralPoolUpdated: TypedContractEvent<
      ReferralPoolUpdatedEvent.InputTuple,
      ReferralPoolUpdatedEvent.OutputTuple,
      ReferralPoolUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
