
ALTER TABLE launch_rounds DROP CONSTRAINT launch_rounds_status_check;
ALTER TABLE launch_rounds ADD CONSTRAINT launch_rounds_status_check 
  CHECK (status = ANY (ARRAY['DRAFT','SUBMITTED','SUBMITTED_FOR_REVIEW','APPROVED','APPROVED_TO_DEPLOY','REJECTED','DEPLOYED','ACTIVE','ENDED','FAILED','CANCELLED','FINALIZED']));
